apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: backend
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: gcr.io/iac1-424123/pixelapp:v3
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred
