apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
        - name: frontend-ui
          image: gcr.io/$PROJECT_ID/frontend-ui:$SHORT_SHA
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://backend-service.backend.svc.cluster.local"
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  selector:
    app: frontend-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
