apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-chart.fullname" . }}
  namespace: {{ .Values.namespace | default "frontend" }}
  labels:
    {{- include "frontend-chart.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "frontend-chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
